/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminRegistration: typeof import('./../components/company/AdminRegistration.vue')['default']
    Avatar: typeof import('./../components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./../components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./../components/ui/avatar/AvatarImage.vue')['default']
    Badge: typeof import('./../components/ui/badge/Badge.vue')['default']
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Card: typeof import('./../components/ui/card/Card.vue')['default']
    CardAction: typeof import('./../components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./../components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../components/ui/card/CardTitle.vue')['default']
    Dialog: typeof import('./../components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./../components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./../components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./../components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./../components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./../components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./../components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./../components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./../components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./../components/ui/dialog/DialogTrigger.vue')['default']
    DropDown: typeof import('./../components/ui/form/DropDown.vue')['default']
    DropdownMenu: typeof import('./../components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./../components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./../components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./../components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./../components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./../components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./../components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./../components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./../components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./../components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./../components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    FormControl: typeof import('./../components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./../components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./../components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./../components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./../components/ui/form/FormMessage.vue')['default']
    FormTextField: typeof import('./../components/ui/form/FormTextField.vue')['default']
    Input: typeof import('./../components/form/Input.vue')['default']
    Label: typeof import('./../components/ui/label/Label.vue')['default']
    Register: typeof import('./../components/company/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('../components/form/SelectDropDown.vue')['default']
    SelectDropDown: typeof import('./../components/form/SelectDropDown.vue')['default']
    Sonner: typeof import('./../components/ui/sonner/Sonner.vue')['default']
    Table: typeof import('./../components/ui/table/Table.vue')['default']
    TableBody: typeof import('./../components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./../components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./../components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./../components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./../components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./../components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./../components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./../components/ui/table/TableRow.vue')['default']
    Textarea: typeof import('./../components/ui/textarea/Textarea.vue')['default']
    TextInput: typeof import('./../components/ui/form/TextInput.vue')['default']
  }
}
