// Comprehensive list of international dialing codes used by phone-prefix
// selectors (label = German country name + code, value = the prefix that is
// sent to the backend as `international_prefix`).
//
// The three DACH countries are kept at the top since they are by far the most
// common for this German market; the rest follow alphabetically. Values are
// unique — where several countries share a calling code they are merged into a
// single entry so dropdown selection stays unambiguous.

export interface DialingCodeOption {
  label: string;
  value: string;
}

export const dialingCodeOptions: DialingCodeOption[] = [
  { label: "Deutschland +49", value: "+49" },
  { label: "Österreich +43", value: "+43" },
  { label: "Schweiz +41", value: "+41" },
  { label: "Ägypten +20", value: "+20" },
  { label: "Albanien +355", value: "+355" },
  { label: "Algerien +213", value: "+213" },
  { label: "Andorra +376", value: "+376" },
  { label: "Argentinien +54", value: "+54" },
  { label: "Australien +61", value: "+61" },
  { label: "Bahrain +973", value: "+973" },
  { label: "Bangladesch +880", value: "+880" },
  { label: "Belgien +32", value: "+32" },
  { label: "Bolivien +591", value: "+591" },
  { label: "Bosnien und Herzegowina +387", value: "+387" },
  { label: "Brasilien +55", value: "+55" },
  { label: "Bulgarien +359", value: "+359" },
  { label: "Chile +56", value: "+56" },
  { label: "China +86", value: "+86" },
  { label: "Costa Rica +506", value: "+506" },
  { label: "Dänemark +45", value: "+45" },
  { label: "Ecuador +593", value: "+593" },
  { label: "Estland +372", value: "+372" },
  { label: "Finnland +358", value: "+358" },
  { label: "Frankreich +33", value: "+33" },
  { label: "Georgien +995", value: "+995" },
  { label: "Ghana +233", value: "+233" },
  { label: "Griechenland +30", value: "+30" },
  { label: "Hongkong +852", value: "+852" },
  { label: "Indien +91", value: "+91" },
  { label: "Indonesien +62", value: "+62" },
  { label: "Irak +964", value: "+964" },
  { label: "Iran +98", value: "+98" },
  { label: "Irland +353", value: "+353" },
  { label: "Island +354", value: "+354" },
  { label: "Israel +972", value: "+972" },
  { label: "Italien +39", value: "+39" },
  { label: "Japan +81", value: "+81" },
  { label: "Jemen +967", value: "+967" },
  { label: "Jordanien +962", value: "+962" },
  { label: "Kambodscha +855", value: "+855" },
  { label: "Kanada/USA +1", value: "+1" },
  { label: "Kasachstan/Russland +7", value: "+7" },
  { label: "Katar +974", value: "+974" },
  { label: "Kenia +254", value: "+254" },
  { label: "Kolumbien +57", value: "+57" },
  { label: "Kroatien +385", value: "+385" },
  { label: "Kuwait +965", value: "+965" },
  { label: "Lettland +371", value: "+371" },
  { label: "Libanon +961", value: "+961" },
  { label: "Liechtenstein +423", value: "+423" },
  { label: "Litauen +370", value: "+370" },
  { label: "Luxemburg +352", value: "+352" },
  { label: "Malaysia +60", value: "+60" },
  { label: "Malta +356", value: "+356" },
  { label: "Marokko +212", value: "+212" },
  { label: "Mazedonien +389", value: "+389" },
  { label: "Mexiko +52", value: "+52" },
  { label: "Moldau +373", value: "+373" },
  { label: "Monaco +377", value: "+377" },
  { label: "Montenegro +382", value: "+382" },
  { label: "Neuseeland +64", value: "+64" },
  { label: "Niederlande +31", value: "+31" },
  { label: "Nigeria +234", value: "+234" },
  { label: "Norwegen +47", value: "+47" },
  { label: "Oman +968", value: "+968" },
  { label: "Pakistan +92", value: "+92" },
  { label: "Peru +51", value: "+51" },
  { label: "Philippinen +63", value: "+63" },
  { label: "Polen +48", value: "+48" },
  { label: "Portugal +351", value: "+351" },
  { label: "Rumänien +40", value: "+40" },
  { label: "Saudi-Arabien +966", value: "+966" },
  { label: "Schweden +46", value: "+46" },
  { label: "Serbien +381", value: "+381" },
  { label: "Singapur +65", value: "+65" },
  { label: "Slowakei +421", value: "+421" },
  { label: "Slowenien +386", value: "+386" },
  { label: "Spanien +34", value: "+34" },
  { label: "Sri Lanka +94", value: "+94" },
  { label: "Südafrika +27", value: "+27" },
  { label: "Südkorea +82", value: "+82" },
  { label: "Taiwan +886", value: "+886" },
  { label: "Thailand +66", value: "+66" },
  { label: "Tschechien +420", value: "+420" },
  { label: "Tunesien +216", value: "+216" },
  { label: "Türkei +90", value: "+90" },
  { label: "Ukraine +380", value: "+380" },
  { label: "Ungarn +36", value: "+36" },
  { label: "Vereinigte Arabische Emirate +971", value: "+971" },
  { label: "Vereinigtes Königreich +44", value: "+44" },
  { label: "Vietnam +84", value: "+84" },
  { label: "Zypern +357", value: "+357" },
];
