/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./layouts/AuthLayout.vue')['default']
    FormLabel: typeof import('./components/ui/form/FormLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./components/ui/form/TextInput.vue')['default']
  }
}
